// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[...page].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about/cv.tsx";
import * as $3 from "./routes/about/index.tsx";
import * as $4 from "./routes/blog/[slug].tsx";
import * as $5 from "./routes/blog/index.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/logs/[log].tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[...page].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about/cv.tsx": $2,
    "./routes/about/index.tsx": $3,
    "./routes/blog/[slug].tsx": $4,
    "./routes/blog/index.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/logs/[log].tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
