export const redirects: Record<string, string> = {
  "/about/cv": "/cv",
  "/about/uses": "/uses",
  "/feedroll": "/blogroll",
  "/logs/feedroll": "/blogroll",
  "/bookmarks": "/logs",
  "/contact": "/connect",
  "/hello": "/connect",
  "/games": "/logs/games",
  "/logs/timeline": "/logs",
  "/no": "/",
  "/no/about": "/about",
  "/no/blog": "/blog",
  "/no/connect": "/connect",
  "/no/garden": "/garden",
  "/no/garden/security": "/garden/security",
  "/no/garden/security/password": "/garden/security/password",
  "/no/privacy": "/privacy",
  "/no/sitemap": "/sitemap",
  "/no/stats": "/stats",
  "/no/work": "/projects",
  "/no/blog/hvordan-det-er-aa-ikke-vaere-kunde-hos-nextgentel":
    "/blog/hvordan-det-er-aa-ikke-vaere-kunde-hos-nextgentel.no",
  "/no/blog/oversatt-til-norsk": "/blog/oversatt-til-norsk.no",
  "/work": "/projects",
  "/read": "/logs/reading",
  "/reading": "/logs/reading",
  "/resume": "/cv",
  "/travel": "/logs/travel",
  "/watched": "/logs/watched",
  "/watching": "/logs/watched",
  "/rss.xml": "/feed.xml",
  "/feed": "/feed.xml",
  "/rss": "/feed.xml",
  "/garden/security/password": "/blog/passwords",
  "/garden/security/password.no": "/blog/passwords",
  "/garden/tools/gpg": "/blog/getting-started-gpg",
  "/garden/tools/git": "/blog/git-tips-and-tricks",
  "/garden/tools/zint": "/blog/qr-codes",
  "/follow": "/subscribe",
  "/feeds": "/subscribe",
  "/podroll": "/blogroll#podcasts",
  "/defaults": "/uses",
  "/wishlist": "/wish",
} as const;
